# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CUSD_Equity_Symposium' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CUSD_Equity_Symposium
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'IQKeyboardManagerSwift'
	pod 'CalendarKit'
	pod 'GoogleMaps'
	pod 'GooglePlaces'
end
